name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-libchardet-fedora-38:
    name: "Fedora 38 - Build Chardet with all dependencies"
    runs-on: ubuntu-latest
    container: "fedora:38"
    steps:
      - name: "Show Head Commit"
        env:
          CONTENT: ${{ toJSON(github.event.head_commit) }}
        run: echo "$CONTENT"
      - name: "update packages"
        run: dnf update -y
      - name: "install sudo,git"
        run: dnf install -y sudo git cmake gcc procps
      - name: "System Information"
        run: |
          echo === uname === 
          uname -a
          echo === /etc/os-release === 
          cat /etc/os-release
          echo === df -hl === 
          df -hl 
          echo === nproc === 
          nproc || true
          echo === free -h === 
          free -h
          echo === top === 
          top -b -n1 -1 -Eg || timeout 1 top -b -n1 
          echo === env === 
          env
          echo === gcc -v === 
          gcc -v
      - name: "checkout sources"
        uses: actions/checkout@v3
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck
      - name: make rpm
        run: make rpm
