name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-libchardet-ubuntu-22:
    name: "Ubuntu-22 - Build Chardet with all dependencies"
    runs-on: ubuntu-22.04
    steps:
      - name: "Show Head Commit"
        env:
          CONTENT: ${{ toJSON(github.event.head_commit) }}
        run: echo "$CONTENT"
      - name: "update packages"
        run: sudo apt-get update
      - name: "install dependencies"
        run: sudo apt-get install -y sudo git automake make autoconf m4 libtool gcc g++ procps jq jo
      - name: "System Information"
        run: |
          echo === uname ===
          uname -a
          echo === /etc/os-release ===
          cat /etc/os-release
          echo === df -hl ===
          df -hl
          echo === nproc ===
          nproc || true
          echo === free -h ===
          free -h
          echo === top ===
          top -b -n1 -1 -Eg || timeout 1 top -b -n1
          echo === env ===
          env
          echo === cc -v ===
          cc -v
          echo === g++ -v ===
          g++ -v
          echo === pwd ===
          pwd
          echo === \$HOME ===
          echo $HOME
      - name: "checkout sources"
        uses: actions/checkout@v3
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check

  build-libchardet-centos8-latest:
    name: "CentOS/8.5 - Build Chardet with all dependencies"
    runs-on: ubuntu-latest
    # Docker container image name
    container: "centos:latest"
    steps:
      - name: "Show Head Commit"
        env:
          CONTENT: ${{ toJSON(github.event.head_commit) }}
        run: echo "$CONTENT"
      - name: "patch CentOS Sources location (1st time)"
        # CentOS 8.2 and later was changed into "CentOS Stream".
        # Around the same time, CentOS 8.1 became EOL (End-Of-Life),
        # And the repositories were moved to the legacy "vault.centos.org" URL.
        # Patch the yum config file to this new location.
        run: |
          cd /etc/yum.repos.d/
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
      - name: "update packages"
        # stock centos has a problem with CMAKE, fails with:
        #  "cmake: symbol lookup error: cmake: undefined symbol: archive_write_add_filter_zstd"
        # updating solves it
        run: dnf update -y
      - name: "patch CentOS Sources location (again...)"
        # The "dnf update -y" above overwrites the yum configuration files,
        # patch them again to point to the vault URLs.
        run: |
          cd /etc/yum.repos.d/
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
      - name: "install dependencies"
        run: dnf install -y sudo git automake make autoconf m4 libtool gcc gcc-c++ procps jq rpm-build rpm-sign
      - name: "System Information"
        run: |
          echo === uname ===
          uname -a
          echo === /etc/os-release ===
          cat /etc/os-release
          echo === /etc/centos-release ===
          cat /etc/centos-release
          echo === df -hl ===
          df -hl
          echo === nproc ===
          nproc || true
          echo === free -h ===
          free -h
          echo === top ===
          top -b -n1 -1 -Eg || timeout 1 top -b -n1
          echo === env ===
          env
          echo === gcc -v ===
          gcc -v
          echo === pwd ===
          pwd
          echo === \$HOME ===
          echo $HOME
      - name: "checkout sources"
        uses: actions/checkout@v3
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check


  build-libchardet-fedora-38:
    name: "Fedora 38 - Build Chardet with all dependencies"
    runs-on: ubuntu-latest
    container: "fedora:38"
    steps:
      - name: "Show Head Commit"
        env:
          CONTENT: ${{ toJSON(github.event.head_commit) }}
        run: echo "$CONTENT"
      - name: "update packages"
        run: dnf update -y
      - name: "install dependencies"
        run: dnf install -y sudo git automake make autoconf m4 libtool gcc gcc-c++ procps jq jo rpm-build rpm-sign
      - name: "System Information"
        run: |
          echo === uname ===
          uname -a
          echo === /etc/os-release ===
          cat /etc/os-release
          echo === df -hl ===
          df -hl
          echo === nproc ===
          nproc || true
          echo === free -h ===
          free -h
          echo === top ===
          top -b -n1 -1 -Eg || timeout 1 top -b -n1
          echo === env ===
          env
          echo === gcc -v ===
          gcc -v
          echo === pwd ===
          pwd
          echo === \$HOME ===
          echo $HOME
      - name: "checkout sources"
        uses: actions/checkout@v3
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
